name: HTTBows
version: '1.0'
main: httbows.httbows.HTTBows
commands:
  HTTbows:
    description: Main Command
    aliases: [explosivebow, thunderbow, shadowbow, levitationbow, firebow]
api-version: 1.19
authors: [ RedRiotTank ]
description: More bows for minecraft plugin
